import { create } from 'zustand';

const useMainStore = create((set) => ({
    userData: {
        sex: 0,
        age: 0,
        weight: 0,
        height: 0,
        // status: 0,
        occupation: 0,
        exertionOccupation: 0,
        province: '',
        livingDuration: 0,
        fattyLiver: 0,
        coronaryAetery: 0,
        chronicKidney: 0,
        diseaseFamily: 0,
        smoking: 0,
        alcohol: 0,
        exercise: 0,
        exerciseDuration: 0,
        sleepDuration: 0,
        socialTime: 0,
        // mask: 0,
        eatSaltedFish: 0,
        eatSausage: 0,
        eatFriedFood: 0,
        eatCoconutMilk: 0,
        eatCandy: 0,
        drinkCoffee: 0,
        // eatGreen: 0,
        eatNut: 0,
        eatFruit: 0,
        eatInPlastic: 0,
        drinkWater: 0,
        //chronicDisease: '',
        q1_health: 0,
        q2_pain: 0,
        q3_physical: 0,
        q4_sleep: 0,
        q5_feeling: 0,
        q6_concentration: 0,
        q7_self: 0,
        q8_bodyImage: 0,
        q9_negativeFeel: 0,
        q10_dailyActivity: 0,
        q11_onMedication: 0,
        q12_working: 0,
        q13_relationship: 0,
        q14_socialSupport: 0,
        q15_safety: 0,
        q16_home: 0,
        q17_financial: 0,
        q18_healthService: 0,
        q19_information: 0,
        q20_leisure: 0,
        q21_goodPhysical: 0,
        q22_transportation: 0,
        q23_spirituality: 0,
        q24_mobility: 0,
        q25_sex: 0,
        q26_level: 0,
        systolic: 0,
        diastolic: 0,
        plasmaGlucose: 0,
        plasmaInsulin: 0,
        HbA1C: 0,
        HDL_cholesterol: 0,
        LDL_cholesterol: 0,
        triglyceride: 0,
        creatinine: 0,
        microalbumin: 0,
        f1_convenient: 0,
        f2_question: 0,
        f3_beautiful: 0,
        f4_fast: 0,
    },
    resultDiabetesData: {
        prediction: 0,
        risk_level: '',
        risk_percentage: 0,
        features_used: [],
    },
    resultHypertentionData: {
        prediction: 0,
        risk_level: '',
        risk_percentage: 0,
        features_used: [],
    },
    setUserData: (data) => set((state) => ({
        userData: { ...state.userData, ...data },
    })),
    setResultDiabetesData: (data) => set((state) => ({
        resultDiabetesData: { ...state.resultDiabetesData, ...data }
    })),
    setResultHypertentionData: (data) => set((state) => ({
        resultHypertentionData: { ...state.resultHypertentionData, ...data }
    })),
    resetUserData: () => set({
        userData: {
            sex: 0,
            age: 0,
            weight: 0,
            height: 0,
            // status: 0,
            occupation: 0,
            exertionOccupation: 0,
            province: '',
            livingDuration: 0,
            fattyLiver: 0,
            coronaryAetery: 0,
            chronicKidney: 0,
            diseaseFamily: 0,
            smoking: 0,
            alcohol: 0,
            exercise: 0,
            exerciseDuration: 0,
            sleepDuration: 0,
            socialTime: 0,
            // mask: 0,
            eatSaltedFish: 0,
            eatSausage: 0,
            eatFriedFood: 0,
            eatCoconutMilk: 0,
            eatCandy: 0,
            drinkCoffee: 0,
            // eatGreen: 0,
            eatNut: 0,
            eatFruit: 0,
            eatInPlastic: 0,
            drinkWater: 0,
            //chronicDisease: '',
            q1_health: 0,
            q2_pain: 0,
            q3_physical: 0,
            q4_sleep: 0,
            q5_feeling: 0,
            q6_concentration: 0,
            q7_self: 0,
            q8_bodyImage: 0,
            q9_negativeFeel: 0,
            q10_dailyActivity: 0,
            q11_onMedication: 0,
            q12_working: 0,
            q13_relationship: 0,
            q14_socialSupport: 0,
            q15_safety: 0,
            q16_home: 0,
            q17_financial: 0,
            q18_healthService: 0,
            q19_information: 0,
            q20_leisure: 0,
            q21_goodPhysical: 0,
            q22_transportation: 0,
            q23_spirituality: 0,
            q24_mobility: 0,
            q25_sex: 0,
            q26_level: 0,
            systolic: 0,
            diastolic: 0,
            plasmaGlucose: 0,
            plasmaInsulin: 0,
            HbA1C: 0,
            HDL_cholesterol: 0,
            LDL_cholesterol: 0,
            triglyceride: 0,
            creatinine: 0,
            microalbumin: 0,
            f1_convenient: 0,
            f2_question: 0,
            f3_beautiful: 0,
            f4_fast: 0,
        }
    }),
    resetResultDiabetesData: () => set(() => ({
        resultDiabetesData: {
            prediction: 0,
            risk_level: '',
            risk_percentage: 0,
            features_used: [],
        }
    })),
    resetResultHypertentionData: () => set(() => ({
        resultHypertentionData: {
            prediction: 0,
            risk_level: '',
            risk_percentage: 0,
            features_used: [],
        }
    })),
}));

export default useMainStore;